### ISSUE TITLE
Wrong syntax in one of the ANXS/Postgresql templates

### ISSUE THREAD

**Issue by plogerais** [bird-house/ansible-wps-playbook#89]
In line 9 of the file `roles/ANXS.postgresql/templates/etc_systemd_system_postgresql.service.d_custom.conf.j2`, the following line causes an error :

```{% if postgresql_version | version_compare('10', '>=') %}```

Here is what the message looks like : 
```TASK [ANXS.postgresql : PostgreSQL | Use the conf directory when starting the Postgres service | RedHat]  

fatal: [wpstest]: FAILED! => {"changed": false, "msg": "AnsibleError: template error while templating string: no filter named 'version_compare'. String: # {{ ansible_managed }}\n# Systemd unit file override to specify user/group as well a
s separate config\n# and data directories.\n[Service]\nUser={{ postgresql_service_user }}\nGroup={{ postgresql_service_group }}\n\nEnvironment=PGDATA={{ postgresql_conf_directory }}\nExecStartPre=\n{% if postgresql_version | version_compa
re('10', '>=') %}\nExecStartPre={{ postgresql_bin_directory }}/postgresql-{{ postgresql_version_terse }}-check-db-dir {{ postgresql_data_directory }}\n{% else %}\nExecStartPre={{ postgresql_bin_directory }}/postgresql{{ postgresql_version
_terse }}-check-db-dir {{ postgresql_data_directory }}\n{% endif %}\n"}
```

It’s possible to correct the error by changing the line in the template to this : 

```{% if postgresql_version is version_compare('10', '>=') %}```

It seems like there is an older version of ANXS/postgresql bundled into ansible-wps-playbook, as this correction is already present in their repo : https://github.com/ANXS/postgresql/blob/master/templates/etc_systemd_system_postgresql.service.d_custom.conf.j2

**Comment by cehbrecht** [comment]
The master branch does not pin the versions of the roles anymore:
https://github.com/bird-house/ansible-wps-playbook/pull/84

I tried with:
```
make clean
make roles
vagrant up
```

It fetches the postgresql role v1.11.1 which already includes this fix.
