### ISSUE TITLE
install additional conda packages may fail

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/ansible-wps-playbook#96]
This playbook installs additional conda packages (gunicorn, ...) needed for deployment. Installation may fail due to package dependencies (exsiting env with "conda-forge" .... update with "default" channel):
https://github.com/bird-house/ansible-wps-playbook/blob/d0161c618f7572f79f2e4f2cde7c986f67e58c52/roles/pywps/tasks/conda.yml#L13

Is there a conda option to prevent this? Use pip instead?

**Comment by tlvu** [comment]
> Is there a conda option to prevent this? Use pip instead?

Have to conda install with the same list of channels, keeping also the same precedence ordering as the original `environment.yml` file, ex: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/441edde3b381eff7ce82e5a171323b31196553be/docker/Dockerfile#L30

**Comment by cehbrecht** [comment]
@tlvu I think the easiest for now would be just to use `pip` ... I only need to install `gunicorn` and optionally `psycopg2`. Otherwise I would need to figure out the channel list used in the environment.

**Comment by tlvu** [comment]
> @tlvu I think the easiest for now would be just to use `pip` ... I only need to install `gunicorn` and optionally `psycopg2`. Otherwise I would need to figure out the channel list used in the environment.

Mostly the channel list is only `conda-forge`and `defaults`.  If there are extra channels, they should "theoretically" not overshadow the releases in `conda-forge` and `defaults` so we could probably have skipped them safely.

Pip is fine when the new packages are pure python packages, not containing C-extensions that requires other system packages.

So bottom line is pip might not work in all cases, but if it works for this specific case, fine.
